name: Export Unity Package

on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - master
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v6
        with:
          go-version-file: 'DreamBiteApp~/go.mod'
      - run: go version

      - name: Environment variables
        run: |
          AUTHOR_NAME="GhostIAm"
          AUTHOR_NAME_GUID="e11b5888f395e5148ad8a63f9997e36b"
          PACKAGE_NAME="DreamBite"
          PACKAGE_NAME_GUID="8b6d297d99f24fd7bfb0c3b8c6ca3c5d"
          VERSION=$GITHUB_REF_NAME-$(git rev-parse --short "$GITHUB_SHA")
          
          # Export variables for use in other steps
          echo "AUTHOR_NAME=$AUTHOR_NAME" >> $GITHUB_ENV
          echo "AUTHOR_NAME_GUID=$AUTHOR_NAME_GUID" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_NAME_GUID=$PACKAGE_NAME_GUID" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install rsync and zip if not already installed
        run: |
          if ! command -v rsync &> /dev/null; then
            sudo apt-get update && sudo apt-get install rsync -y
          fi
          if ! command -v zip &> /dev/null; then
            sudo apt-get update && sudo apt-get install zip -y
          fi

      - name: Prepare assets
        run: |
          AUTHOR_ASSETS_PATH="Assets/$AUTHOR_NAME"
          PACKAGE_ASSETS_PATH="Assets/$AUTHOR_NAME/$PACKAGE_NAME"
          
          mkdir -p "$PACKAGE_ASSETS_PATH"
          # Copy all files except Assets folder. 
          rsync -a --exclude Assets * "./$PACKAGE_ASSETS_PATH"
          
          printf "fileFormatVersion: 2\nguid: $AUTHOR_NAME_GUID\nfolderAsset: yes" > "./$AUTHOR_ASSETS_PATH.meta"
          printf "fileFormatVersion: 2\nguid: $PACKAGE_NAME_GUID\nfolderAsset: yes" > "./$PACKAGE_ASSETS_PATH.meta"
          echo "Assets/$AUTHOR_NAME.meta" > metaList
          echo "$PACKAGE_ASSETS_PATH.meta" >> metaList
          echo "$VERSION" > "$PACKAGE_ASSETS_PATH/version.txt"
          find "$PACKAGE_ASSETS_PATH/" -name \*.meta >> metaList
          
          ls -la "$PACKAGE_ASSETS_PATH/"
          cat metaList
          
          mkdir export

      - uses: pCYSl5EDgo/create-unitypackage@master
        with:
          package-path: "export/${{ env.PACKAGE_NAME }}_${{ env.VERSION }}.unitypackage"
          include-files: metaList
          
      - name: Build DreamBiteApp
        run: |
          cd ./DreamBiteApp~
          GOOS=windows GOARCH=amd64 go build -o ../export/DreamBiteApp.exe .

      - name: Compress files to zip
        run: |
          cd export/
          zip -r "../${{ env.PACKAGE_NAME }}_${{ env.VERSION }}.zip" "."

      - uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "${{ env.PACKAGE_NAME }}_${{ env.VERSION }}.zip"
          draft: true

      - name: Upload artifact (Gitea)
        if: ${{ !startsWith(github.ref, 'refs/tags/') && env.GITEA_ACTIONS == 'true' }}
        uses: christopherHX/gitea-upload-artifact@v4
        with:
          path: "${{ env.PACKAGE_NAME }}_${{ env.VERSION }}.zip"
          name: ${{ env.PACKAGE_NAME }}_${{ env.VERSION }}

      - name: Upload artifact (GitHub)
        if: ${{ !startsWith(github.ref, 'refs/tags/') && env.GITEA_ACTIONS == '' }}
        uses: actions/upload-artifact@v4
        with:
          path: "${{ env.PACKAGE_NAME }}_${{ env.VERSION }}.zip"
          name: ${{ env.PACKAGE_NAME }}_${{ env.VERSION }}
